name: cooljeanius/bnetd
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are currently unsupported
#     # 'compiler' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: cd bnetd/bnetd-0.4.27.2/src && ./configure --with-warn && make
    - run: pwd
      if: "${{ success() }}"
    strategy:
      matrix:
        compiler:
        - clang
        - gcc
